import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AlertShowHideProvider } from "./context/AlertContext";
import Link from "next/link";
import { HomeRepairServiceOutlined } from "@mui/icons-material";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "To do list",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
   <div className="w-full bg-amber-400 shadow-sm">
  <nav className="max-w-4xl mx-auto px-4 py-3 flex items-center gap-4">
    <Link 
      href={"/"} 
      className="text-gray-900 font-medium px-3 py-2 rounded-md hover:bg-amber-500 transition-colors duration-200 flex items-center gap-1"
    >
      <HomeRepairServiceOutlined className="w-5 h-5" /> {/* Optional icon */}
      <span>Home</span>
    </Link>
    <Link 
      href={"/task/add"} 
      className="text-gray-900 font-medium px-3 py-2 rounded-md hover:bg-amber-500 transition-colors duration-200 flex items-center gap-1"
    >
      <HomeRepairServiceOutlined className="w-5 h-5" /> {/* Optional icon */}
      <span>Add Task</span>
    </Link>
  </nav>
</div>
        <AlertShowHideProvider>{children}</AlertShowHideProvider>
      </body>
    </html>
  );
}
